export const boxersList = [
    {
        name: "Muhammad Ali",
        division: "heavy",
        fights: 61,
        win: 56,
        loss: 5,
        kos: 37,
    },
    {
        name: "Mike Tyson",
        division: "heavy",
        fights: 58,
        win: 50,
        loss: 6,
        kos: 44,
    },
    {
        name: "Anthony Joshua",
        division: "heavy",
        fights: 25,
        win: 24,
        loss: 1,
        kos: 22,
    },
    {
        name: "Tyson Fury",
        division: "heavy",
        fights: 31,
        win: 30,
        loss: 0,
        kos: 21,
    },
    {
        name: "Deontay Wilder",
        division: "heavy",
        fights: 45,
        win: 42,
        loss: 1,
        kos: 41,
    },
    {
        name: "Oleksandr Usyk",
        division: "heavy",
        fights: 19,
        win: 18,
        loss: 1,
        kos: 13,
    },
    {
        name: "Andy Ruiz Jr.",
        division: "heavy",
        fights: 36,
        win: 34,
        loss: 2,
        kos: 22,
    },
    {
        name: "Dillian Whyte",
        division: "heavy",
        fights: 29,
        win: 28,
        loss: 1,
        kos: 19,
    },
    {
        name: "Joseph Parker",
        division: "heavy",
        fights: 30,
        win: 29,
        loss: 1,
        kos: 21,
    },
    {
        name: "Luis Ortiz",
        division: "heavy",
        fights: 35,
        win: 32,
        loss: 3,
        kos: 27,
    },
    {
        name: "Adam Kownacki",
        division: "heavy",
        fights: 21,
        win: 20,
        loss: 1,
        kos: 15,
    },
    {
        name: "Michael Hunter",
        division: "heavy",
        fights: 21,
        win: 19,
        loss: 1,
        kos: 12,
    },
    {
        name: "Carlos Takam",
        division: "heavy",
        fights: 45,
        win: 39,
        loss: 5,
        kos: 28,
    },
    {
        name: "Kubrat Pulev",
        division: "heavy",
        fights: 29,
        win: 28,
        loss: 1,
        kos: 14,
    },
    {
        name: "Charles Martin",
        division: "heavy",
        fights: 30,
        win: 29,
        loss: 1,
        kos: 25,
    },
    {
        name: "Agit Kabayel",
        division: "heavy",
        fights: 25,
        win: 25,
        loss: 0,
        kos: 15,
    },
    {
        name: "Larry Holmes",
        division: "heavy",
        fights: 75,
        win: 69,
        loss: 6,
        kos: 44,
    },
    {
        name: "George Foreman",
        division: "heavy",
        fights: 81,
        win: 76,
        loss: 5,
        kos: 68,
    },
    {
        name: "Joe Frazier",
        division: "heavy",
        fights: 37,
        win: 32,
        loss: 4,
        kos: 27,
    },
    {
        name: "Evander Holyfield",
        division: "heavy",
        fights: 57,
        win: 44,
        loss: 10,
        kos: 29,
    },
    {
        name: "Lennox Lewis",
        division: "heavy",
        fights: 44,
        win: 41,
        loss: 2,
        kos: 32,
    },
    {
        name: "Riddick Bowe",
        division: "heavy",
        fights: 45,
        win: 43,
        loss: 1,
        kos: 33,
    },
    {
        name: "Floyd Mayweather Jr.",
        division: "welterweight",
        fights: 50,
        win: 50,
        loss: 0,
        kos: 27,
    },
    {
        name: "Manny Pacquiao",
        division: "welterweight",
        fights: 72,
        win: 62,
        loss: 7,
        kos: 39,
    },
    {
        name: "Sugar Ray Robinson",
        division: "middleweight",
        fights: 200,
        win: 173,
        loss: 19,
        kos: 108,
    },
    {
        name: "Marvin Hagler",
        division: "middleweight",
        fights: 67,
        win: 62,
        loss: 3,
        kos: 52,
    },
    {
        name: "Roy Jones Jr.",
        division: "light heavyweight",
        fights: 75,
        win: 66,
        loss: 9,
        kos: 47,
    },
    {
        name: "Bernard Hopkins",
        division: "middleweight",
        fights: 67,
        win: 55,
        loss: 8,
        kos: 32,
    },
    {
        name: "Miguel Cotto",
        division: "welterweight",
        fights: 47,
        win: 41,
        loss: 6,
        kos: 33,
    },
    {
        name: "Canelo Alvarez",
        division: "super middleweight",
        fights: 58,
        win: 56,
        loss: 1,
        kos: 38,
    },
    {
        name: "Oscar De La Hoya",
        division: "welterweight",
        fights: 45,
        win: 39,
        loss: 6,
        kos: 30,
    },
    {
        name: "Julio Cesar Chavez Sr.",
        division: "lightweight",
        fights: 115,
        win: 107,
        loss: 6,
        kos: 86,
    },
    {
        name: "Roberto Duran",
        division: "lightweight",
        fights: 119,
        win: 103,
        loss: 16,
        kos: 70,
    },
    {
        name: "Sugar Ray Leonard",
        division: "welterweight",
        fights: 40,
        win: 36,
        loss: 3,
        kos: 25,
    },
    {
        name: "Tommy Hearns",
        division: "super welterweight",
        fights: 67,
        win: 61,
        loss: 5,
        kos: 48,
    },
    {
        name: "Aaron Pryor",
        division: "super lightweight",
        fights: 39,
        win: 39,
        loss: 1,
        kos: 35,
    },
    {
        name: "Pernell Whitaker",
        division: "lightweight",
        fights: 46,
        win: 40,
        loss: 4,
        kos: 17,
    },
    {
        name: "Mike McCallum",
        division: "super welterweight",
        fights: 58,
        win: 49,
        loss: 5,
        kos: 36,
    },
    {
        name: "Erik Morales",
        division: "super bantamweight",
        fights: 52,
        win: 52,
        loss: 9,
        kos: 36,
    },
    {
        name: "Marco Antonio Barrera",
        division: "super featherweight",
        fights: 75,
        win: 67,
        loss: 7,
        kos: 44,
    },
    {
        name: "Arturo Gatti",
        division: "super lightweight",
        fights: 49,
        win: 40,
        loss: 9,
        kos: 31,
    },
    {
        name: "Diego Corrales",
        division: "super featherweight",
        fights: 40,
        win: 31,
        loss: 4,
        kos: 27,
    },
    {
        name: "Fernando Vargas",
        division: "super welterweight",
        fights: 37,
        win: 26,
        loss: 5,
        kos: 22,
    },
    {
        name: "Sonny Liston",
        division: "heavy",
        fights: 54,
        win: 50,
        loss: 4,
        kos: 39,
    },
    {
        name: "Joe Louis",
        division: "heavy",
        fights: 69,
        win: 66,
        loss: 3,
        kos: 52,
    },
    {
        name: "Rocky Marciano",
        division: "heavy",
        fights: 49,
        win: 49,
        loss: 0,
        kos: 43,
    },
    {
        name: "Jack Dempsey",
        division: "heavy",
        fights: 83,
        win: 64,
        loss: 6,
        kos: 49,
    },
    {
        name: "Joe Walcott",
        division: "heavy",
        fights: 68,
        win: 51,
        loss: 18,
        kos: 32,
    },
];
